//! Placeholder until the sweep: no shape is taken. Generated by scripts/groupby_table.py.

pub(crate) struct Row {
    pub family: &'static str,
    pub keys: &'static str,
    pub key_class: &'static str,
    pub source: &'static str,
    pub bucket: &'static str,
    pub min_rows: Option<u64>,
    pub max_rows: Option<u64>,
    pub ratios: &'static [(u64, f64)],
}

pub(crate) const SOURCE: &str = "no sweep yet";
pub(crate) const NEAR_ROWS: u64 = 4;
pub(crate) const ROWS_BUCKET: &str = "rows/2";
pub(crate) const BUCKETS: &[(&str, u64, u64)] =
    &[("200", 1, 1_414), ("10k", 1_415, 31_622), ("100k", 31_623, 316_227), ("1M", 316_228, 3_162_277)];
pub(crate) const TABLE: &[Row] = &[];
