//! The measured aggregate table. Generated by scripts/groupby_table.py from
//! results/datafusion_groupby_sweep_2026-09-29.csv; do not edit by hand (`--check` fails when this file and that one disagree).
//! check: results/datafusion_groupby_default_2026-09-29.csv
//! check: results/datafusion_groupby_default_taken_2026-09-29.csv
//! check: results/datafusion_groupby_default_cap_2026-09-29.csv
//! check: results/datafusion_groupby_default_idle_2026-09-29.csv
//! check: results/datafusion_groupby_default_handback_2026-09-29.csv
//! check: results/datafusion_groupby_recheck_gpu_2026-09-29.csv
//! check: results/datafusion_groupby_recheck_2026-09-29.csv
//! check: results/datafusion_groupby_recheck2_2026-09-29.csv
//!
//! One row per (aggregate family, key count, key class, input, group-count bucket) the sweep
//! measured: `min_rows` is the fewest input rows from which ArrowMetal was measured at least
//! MIN_RATIO x HEADROOM (1.5 x 1.1) ahead of DataFusion alone at that size and every
//! larger one (None: not taken at any size); `max_rows` caps a take whose ratio fell between the
//! two largest sizes; `ratios` is the worst ratio (both layouts, every case of the family) per size.
//! The `check:` files raise `min_rows` where the default's first run after idle is below
//! 1.0x of DataFusion alone warm, or a run-time hand-back of the shape below 0.97x
//! (best and median of rounds); the reason follows the row.

pub(crate) struct Row {
    pub family: &'static str,
    pub keys: &'static str,
    pub key_class: &'static str,
    pub source: &'static str,
    pub bucket: &'static str,
    pub min_rows: Option<u64>,
    pub max_rows: Option<u64>,
    pub ratios: &'static [(u64, f64)],
}

pub(crate) const SOURCE: &str = "results/datafusion_groupby_sweep_2026-09-29.csv";
pub(crate) const MIN_RATIO: f64 = 1.5;
pub(crate) const HEADROOM: f64 = 1.1;
pub(crate) const NEAR_ROWS: u64 = 4;
pub(crate) const ROWS_BUCKET: &str = "rows/2";
pub(crate) const BUCKETS: &[(&str, u64, u64)] = &[("200", 1, 1414), ("10k", 1415, 31622), ("100k", 31623, 316227), ("1M", 316228, 3162277)];

pub(crate) const TABLE: &[Row] = &[
    Row { family: "count", keys: "1", key_class: "i32", source: "memory", bucket: "200", min_rows: None, max_rows: None, ratios: &[(1000000, 0.44), (2000000, 0.4), (5000000, 0.64), (10000000, 0.91), (50000000, 1.6)] },
    Row { family: "count", keys: "1", key_class: "i32", source: "memory", bucket: "10k", min_rows: None, max_rows: None, ratios: &[(1000000, 0.73), (2000000, 0.72), (5000000, 0.67), (10000000, 1.2), (50000000, 1.5)] },
    Row { family: "count", keys: "1", key_class: "i32", source: "memory", bucket: "100k", min_rows: None, max_rows: None, ratios: &[(1000000, 1.2), (2000000, 2.1), (5000000, 1.4), (10000000, 2.8), (50000000, 2.4)] }, // first run after idle below DataFusion alone at every size
    Row { family: "count", keys: "1", key_class: "i32", source: "memory", bucket: "1M", min_rows: None, max_rows: None, ratios: &[(5000000, 2.2), (10000000, 1.9), (50000000, 3.4)] }, // first run after idle below DataFusion alone at every size
    Row { family: "count", keys: "1", key_class: "i32", source: "memory", bucket: "rows/2", min_rows: None, max_rows: None, ratios: &[(1000000, 1.2), (2000000, 1.4), (5000000, 1.3), (10000000, 1.9), (50000000, 0.9)] },
    Row { family: "count", keys: "1", key_class: "i64", source: "memory", bucket: "200", min_rows: None, max_rows: None, ratios: &[(1000000, 0.4), (2000000, 0.58), (5000000, 0.67), (10000000, 0.98), (50000000, 1.3)] },
    Row { family: "count", keys: "1", key_class: "i64", source: "memory", bucket: "10k", min_rows: None, max_rows: None, ratios: &[(1000000, 0.7), (2000000, 0.7), (5000000, 0.99), (10000000, 1.1), (50000000, 1.3)] },
    Row { family: "count", keys: "1", key_class: "i64", source: "memory", bucket: "100k", min_rows: None, max_rows: None, ratios: &[(1000000, 1.2), (2000000, 2.0), (5000000, 2.2), (10000000, 2.5), (50000000, 2.5)] }, // first run after idle below DataFusion alone at every size
    Row { family: "count", keys: "1", key_class: "i64", source: "memory", bucket: "1M", min_rows: None, max_rows: None, ratios: &[(5000000, 2.2), (10000000, 2.7), (50000000, 3.5)] }, // first run after idle below DataFusion alone at every size
    Row { family: "count", keys: "1", key_class: "i64", source: "memory", bucket: "rows/2", min_rows: None, max_rows: None, ratios: &[(1000000, 1.2), (2000000, 1.6), (5000000, 1.8), (10000000, 1.9), (50000000, 0.89)] },
    Row { family: "count", keys: "2+", key_class: "i32", source: "memory", bucket: "200", min_rows: None, max_rows: None, ratios: &[(1000000, 0.56), (2000000, 0.88), (5000000, 1.2), (10000000, 1.6), (50000000, 2.1)] },
    Row { family: "count", keys: "2+", key_class: "i32", source: "memory", bucket: "10k", min_rows: None, max_rows: None, ratios: &[(1000000, 0.84), (2000000, 0.93), (5000000, 1.4), (10000000, 1.8), (50000000, 2.1)] }, // first run after idle below DataFusion alone at every size
    Row { family: "count", keys: "2+", key_class: "i32", source: "memory", bucket: "100k", min_rows: None, max_rows: None, ratios: &[(1000000, 1.2), (2000000, 1.7), (5000000, 2.5), (10000000, 2.7), (50000000, 3.2)] }, // first run after idle below DataFusion alone at every size
    Row { family: "count", keys: "2+", key_class: "i32", source: "memory", bucket: "1M", min_rows: Some(50000000), max_rows: None, ratios: &[(5000000, 2.0), (10000000, 2.8), (50000000, 4.0)] }, // first run after idle holds from 50M
    Row { family: "count", keys: "2+", key_class: "i32", source: "memory", bucket: "rows/2", min_rows: None, max_rows: None, ratios: &[(1000000, 1.1), (2000000, 1.5), (5000000, 1.9), (10000000, 2.0), (50000000, 0.9)] },
    Row { family: "count", keys: "2+", key_class: "i64", source: "memory", bucket: "200", min_rows: None, max_rows: None, ratios: &[(1000000, 0.53), (2000000, 0.75), (5000000, 1.0), (10000000, 1.4), (50000000, 1.7)] },
    Row { family: "count", keys: "2+", key_class: "i64", source: "memory", bucket: "10k", min_rows: None, max_rows: None, ratios: &[(1000000, 0.81), (2000000, 0.91), (5000000, 1.4), (10000000, 1.6), (50000000, 1.7)] },
    Row { family: "count", keys: "2+", key_class: "i64", source: "memory", bucket: "100k", min_rows: None, max_rows: None, ratios: &[(1000000, 1.3), (2000000, 1.5), (5000000, 2.4), (10000000, 2.7), (50000000, 3.1)] }, // first run after idle below DataFusion alone at every size
    Row { family: "count", keys: "2+", key_class: "i64", source: "memory", bucket: "1M", min_rows: None, max_rows: None, ratios: &[(5000000, 2.1), (10000000, 2.8), (50000000, 3.7)] }, // first run after idle below DataFusion alone at every size
    Row { family: "count", keys: "2+", key_class: "i64", source: "memory", bucket: "rows/2", min_rows: None, max_rows: None, ratios: &[(1000000, 1.2), (2000000, 1.7), (5000000, 1.9), (10000000, 2.0), (50000000, 0.92)] },
    Row { family: "distinct", keys: "1", key_class: "i32", source: "memory", bucket: "200", min_rows: None, max_rows: None, ratios: &[(1000000, 0.48), (2000000, 0.59), (5000000, 0.87), (10000000, 1.1), (50000000, 1.5)] },
    Row { family: "distinct", keys: "1", key_class: "i32", source: "memory", bucket: "10k", min_rows: None, max_rows: None, ratios: &[(1000000, 0.78), (2000000, 0.64), (5000000, 1.1), (10000000, 1.3), (50000000, 1.4)] },
    Row { family: "distinct", keys: "1", key_class: "i32", source: "memory", bucket: "100k", min_rows: None, max_rows: None, ratios: &[(1000000, 1.3), (2000000, 1.5), (5000000, 2.2), (10000000, 2.8), (50000000, 2.0)] }, // first run after idle below DataFusion alone at every size
    Row { family: "distinct", keys: "1", key_class: "i32", source: "memory", bucket: "1M", min_rows: None, max_rows: None, ratios: &[(5000000, 2.2), (10000000, 2.8), (50000000, 2.8)] }, // first run after idle below DataFusion alone at every size
    Row { family: "distinct", keys: "1", key_class: "i32", source: "memory", bucket: "rows/2", min_rows: None, max_rows: None, ratios: &[(1000000, 1.4), (2000000, 1.5), (5000000, 2.2), (10000000, 2.1), (50000000, 0.8)] },
    Row { family: "distinct", keys: "1", key_class: "i64", source: "memory", bucket: "200", min_rows: None, max_rows: None, ratios: &[(1000000, 0.43), (2000000, 0.6), (5000000, 0.7), (10000000, 1.0), (50000000, 1.2)] },
    Row { family: "distinct", keys: "1", key_class: "i64", source: "memory", bucket: "10k", min_rows: None, max_rows: None, ratios: &[(1000000, 0.74), (2000000, 0.66), (5000000, 0.94), (10000000, 1.2), (50000000, 1.3)] },
    Row { family: "distinct", keys: "1", key_class: "i64", source: "memory", bucket: "100k", min_rows: None, max_rows: None, ratios: &[(1000000, 1.3), (2000000, 1.5), (5000000, 2.3), (10000000, 2.4), (50000000, 2.3)] }, // first run after idle below DataFusion alone at every size
    Row { family: "distinct", keys: "1", key_class: "i64", source: "memory", bucket: "1M", min_rows: None, max_rows: None, ratios: &[(5000000, 2.4), (10000000, 2.6), (50000000, 2.7)] }, // first run after idle below DataFusion alone at every size
    Row { family: "distinct", keys: "1", key_class: "i64", source: "memory", bucket: "rows/2", min_rows: None, max_rows: None, ratios: &[(1000000, 1.3), (2000000, 1.4), (5000000, 2.1), (10000000, 2.1), (50000000, 0.83)] },
    Row { family: "distinct", keys: "2+", key_class: "i32", source: "memory", bucket: "200", min_rows: None, max_rows: None, ratios: &[(1000000, 0.56), (2000000, 0.86), (5000000, 1.3), (10000000, 1.7), (50000000, 2.2)] }, // first run after idle below DataFusion alone at every size
    Row { family: "distinct", keys: "2+", key_class: "i32", source: "memory", bucket: "10k", min_rows: None, max_rows: None, ratios: &[(1000000, 0.88), (2000000, 0.98), (5000000, 1.4), (10000000, 1.8), (50000000, 2.1)] }, // first run after idle below DataFusion alone at every size
    Row { family: "distinct", keys: "2+", key_class: "i32", source: "memory", bucket: "100k", min_rows: None, max_rows: None, ratios: &[(1000000, 1.3), (2000000, 1.5), (5000000, 1.7), (10000000, 2.6), (50000000, 3.0)] }, // first run after idle below DataFusion alone at every size
    Row { family: "distinct", keys: "2+", key_class: "i32", source: "memory", bucket: "1M", min_rows: None, max_rows: None, ratios: &[(5000000, 2.1), (10000000, 2.1), (50000000, 3.4)] }, // first run after idle below DataFusion alone at every size
    Row { family: "distinct", keys: "2+", key_class: "i32", source: "memory", bucket: "rows/2", min_rows: None, max_rows: None, ratios: &[(1000000, 1.2), (2000000, 1.7), (5000000, 2.2), (10000000, 2.1), (50000000, 0.84)] },
    Row { family: "distinct", keys: "2+", key_class: "i64", source: "memory", bucket: "200", min_rows: None, max_rows: None, ratios: &[(1000000, 0.57), (2000000, 0.77), (5000000, 1.1), (10000000, 1.5), (50000000, 1.8)] },
    Row { family: "distinct", keys: "2+", key_class: "i64", source: "memory", bucket: "10k", min_rows: None, max_rows: None, ratios: &[(1000000, 0.84), (2000000, 0.88), (5000000, 1.3), (10000000, 1.5), (50000000, 1.9)] },
    Row { family: "distinct", keys: "2+", key_class: "i64", source: "memory", bucket: "100k", min_rows: None, max_rows: None, ratios: &[(1000000, 1.3), (2000000, 1.5), (5000000, 2.5), (10000000, 2.8), (50000000, 3.2)] }, // first run after idle below DataFusion alone at every size
    Row { family: "distinct", keys: "2+", key_class: "i64", source: "memory", bucket: "1M", min_rows: None, max_rows: None, ratios: &[(5000000, 2.1), (10000000, 2.6), (50000000, 3.5)] }, // first run after idle below DataFusion alone at every size
    Row { family: "distinct", keys: "2+", key_class: "i64", source: "memory", bucket: "rows/2", min_rows: None, max_rows: None, ratios: &[(1000000, 1.3), (2000000, 1.8), (5000000, 2.1), (10000000, 2.1), (50000000, 0.86)] },
    Row { family: "minmax_f64", keys: "1", key_class: "i32", source: "memory", bucket: "200", min_rows: None, max_rows: None, ratios: &[(1000000, 0.19), (2000000, 0.19), (5000000, 0.19), (10000000, 0.27), (50000000, 0.37)] },
    Row { family: "minmax_f64", keys: "1", key_class: "i32", source: "memory", bucket: "10k", min_rows: None, max_rows: None, ratios: &[(1000000, 0.38), (2000000, 0.33), (5000000, 0.34), (10000000, 0.32), (50000000, 0.28)] },
    Row { family: "minmax_f64", keys: "1", key_class: "i32", source: "memory", bucket: "100k", min_rows: None, max_rows: None, ratios: &[(1000000, 0.41), (2000000, 0.72), (5000000, 0.84), (10000000, 0.82), (50000000, 0.64)] },
    Row { family: "minmax_f64", keys: "1", key_class: "i32", source: "memory", bucket: "1M", min_rows: None, max_rows: None, ratios: &[(5000000, 0.57), (10000000, 0.62), (50000000, 0.67)] },
    Row { family: "minmax_f64", keys: "1", key_class: "i32", source: "memory", bucket: "rows/2", min_rows: None, max_rows: None, ratios: &[(1000000, 0.42), (2000000, 0.51), (5000000, 0.42), (10000000, 0.4), (50000000, 0.26)] },
    Row { family: "minmax_f64", keys: "1", key_class: "i64", source: "memory", bucket: "200", min_rows: None, max_rows: None, ratios: &[(1000000, 0.16), (2000000, 0.19), (5000000, 0.21), (10000000, 0.27), (50000000, 0.36)] },
    Row { family: "minmax_f64", keys: "1", key_class: "i64", source: "memory", bucket: "10k", min_rows: None, max_rows: None, ratios: &[(1000000, 0.29), (2000000, 0.35), (5000000, 0.36), (10000000, 0.34), (50000000, 0.29)] },
    Row { family: "minmax_f64", keys: "1", key_class: "i64", source: "memory", bucket: "100k", min_rows: None, max_rows: None, ratios: &[(1000000, 0.56), (2000000, 0.7), (5000000, 0.87), (10000000, 0.87), (50000000, 0.73)] },
    Row { family: "minmax_f64", keys: "1", key_class: "i64", source: "memory", bucket: "1M", min_rows: None, max_rows: None, ratios: &[(5000000, 0.57), (10000000, 0.65), (50000000, 0.72)] },
    Row { family: "minmax_f64", keys: "1", key_class: "i64", source: "memory", bucket: "rows/2", min_rows: None, max_rows: None, ratios: &[(1000000, 0.39), (2000000, 0.52), (5000000, 0.46), (10000000, 0.42), (50000000, 0.26)] },
    Row { family: "minmax_f64", keys: "2+", key_class: "i32", source: "memory", bucket: "200", min_rows: None, max_rows: None, ratios: &[(1000000, 0.25), (2000000, 0.31), (5000000, 0.38), (10000000, 0.53), (50000000, 0.62)] },
    Row { family: "minmax_f64", keys: "2+", key_class: "i32", source: "memory", bucket: "10k", min_rows: None, max_rows: None, ratios: &[(1000000, 0.36), (2000000, 0.47), (5000000, 0.55), (10000000, 0.55), (50000000, 0.46)] },
    Row { family: "minmax_f64", keys: "2+", key_class: "i32", source: "memory", bucket: "100k", min_rows: None, max_rows: None, ratios: &[(1000000, 0.58), (2000000, 0.57), (5000000, 1.0), (10000000, 0.98), (50000000, 0.91)] },
    Row { family: "minmax_f64", keys: "2+", key_class: "i32", source: "memory", bucket: "1M", min_rows: None, max_rows: None, ratios: &[(5000000, 0.62), (10000000, 0.71), (50000000, 0.8)] },
    Row { family: "minmax_f64", keys: "2+", key_class: "i32", source: "memory", bucket: "rows/2", min_rows: None, max_rows: None, ratios: &[(1000000, 0.42), (2000000, 0.56), (5000000, 0.47), (10000000, 0.45), (50000000, 0.27)] },
    Row { family: "minmax_f64", keys: "2+", key_class: "i64", source: "memory", bucket: "200", min_rows: None, max_rows: None, ratios: &[(1000000, 0.23), (2000000, 0.31), (5000000, 0.38), (10000000, 0.5), (50000000, 0.62)] },
    Row { family: "minmax_f64", keys: "2+", key_class: "i64", source: "memory", bucket: "10k", min_rows: None, max_rows: None, ratios: &[(1000000, 0.38), (2000000, 0.48), (5000000, 0.55), (10000000, 0.55), (50000000, 0.55)] },
    Row { family: "minmax_f64", keys: "2+", key_class: "i64", source: "memory", bucket: "100k", min_rows: None, max_rows: None, ratios: &[(1000000, 0.56), (2000000, 0.75), (5000000, 0.88), (10000000, 1.0), (50000000, 1.0)] },
    Row { family: "minmax_f64", keys: "2+", key_class: "i64", source: "memory", bucket: "1M", min_rows: None, max_rows: None, ratios: &[(5000000, 0.7), (10000000, 0.82), (50000000, 0.95)] },
    Row { family: "minmax_f64", keys: "2+", key_class: "i64", source: "memory", bucket: "rows/2", min_rows: None, max_rows: None, ratios: &[(1000000, 0.46), (2000000, 0.52), (5000000, 0.52), (10000000, 0.48), (50000000, 0.28)] },
    Row { family: "minmax_int", keys: "1", key_class: "i32", source: "memory", bucket: "200", min_rows: None, max_rows: None, ratios: &[(1000000, 0.37), (2000000, 0.42), (5000000, 0.6), (10000000, 0.7), (50000000, 0.94)] },
    Row { family: "minmax_int", keys: "1", key_class: "i32", source: "memory", bucket: "10k", min_rows: None, max_rows: None, ratios: &[(1000000, 0.66), (2000000, 0.69), (5000000, 0.87), (10000000, 0.74), (50000000, 0.67)] },
    Row { family: "minmax_int", keys: "1", key_class: "i32", source: "memory", bucket: "100k", min_rows: None, max_rows: None, ratios: &[(1000000, 1.2), (2000000, 1.8), (5000000, 2.0), (10000000, 1.8), (50000000, 1.3)] },
    Row { family: "minmax_int", keys: "1", key_class: "i32", source: "memory", bucket: "1M", min_rows: None, max_rows: None, ratios: &[(5000000, 1.6), (10000000, 1.4), (50000000, 1.3)] },
    Row { family: "minmax_int", keys: "1", key_class: "i32", source: "memory", bucket: "rows/2", min_rows: None, max_rows: None, ratios: &[(1000000, 1.3), (2000000, 1.7), (5000000, 1.3), (10000000, 1.1), (50000000, 0.56)] },
    Row { family: "minmax_int", keys: "1", key_class: "i64", source: "memory", bucket: "200", min_rows: None, max_rows: None, ratios: &[(1000000, 0.37), (2000000, 0.48), (5000000, 0.6), (10000000, 0.69), (50000000, 0.84)] },
    Row { family: "minmax_int", keys: "1", key_class: "i64", source: "memory", bucket: "10k", min_rows: None, max_rows: None, ratios: &[(1000000, 0.48), (2000000, 0.77), (5000000, 0.8), (10000000, 0.64), (50000000, 0.66)] },
    Row { family: "minmax_int", keys: "1", key_class: "i64", source: "memory", bucket: "100k", min_rows: None, max_rows: None, ratios: &[(1000000, 1.1), (2000000, 1.8), (5000000, 1.8), (10000000, 1.8), (50000000, 1.5)] },
    Row { family: "minmax_int", keys: "1", key_class: "i64", source: "memory", bucket: "1M", min_rows: None, max_rows: None, ratios: &[(5000000, 1.6), (10000000, 1.4), (50000000, 1.5)] },
    Row { family: "minmax_int", keys: "1", key_class: "i64", source: "memory", bucket: "rows/2", min_rows: None, max_rows: None, ratios: &[(1000000, 1.2), (2000000, 1.8), (5000000, 1.2), (10000000, 1.1), (50000000, 0.56)] },
    Row { family: "minmax_int", keys: "2+", key_class: "i32", source: "memory", bucket: "200", min_rows: None, max_rows: None, ratios: &[(1000000, 0.49), (2000000, 0.74), (5000000, 0.92), (10000000, 1.2), (50000000, 1.4)] },
    Row { family: "minmax_int", keys: "2+", key_class: "i32", source: "memory", bucket: "10k", min_rows: None, max_rows: None, ratios: &[(1000000, 0.79), (2000000, 0.97), (5000000, 1.1), (10000000, 1.1), (50000000, 1.0)] },
    Row { family: "minmax_int", keys: "2+", key_class: "i32", source: "memory", bucket: "100k", min_rows: None, max_rows: None, ratios: &[(1000000, 1.0), (2000000, 1.6), (5000000, 1.9), (10000000, 1.9), (50000000, 1.9)] }, // first run after idle below DataFusion alone at every size
    Row { family: "minmax_int", keys: "2+", key_class: "i32", source: "memory", bucket: "1M", min_rows: None, max_rows: None, ratios: &[(5000000, 1.6), (10000000, 1.6), (50000000, 1.6)] },
    Row { family: "minmax_int", keys: "2+", key_class: "i32", source: "memory", bucket: "rows/2", min_rows: None, max_rows: None, ratios: &[(1000000, 1.3), (2000000, 1.5), (5000000, 1.3), (10000000, 1.1), (50000000, 0.57)] },
    Row { family: "minmax_int", keys: "2+", key_class: "i64", source: "memory", bucket: "200", min_rows: None, max_rows: None, ratios: &[(1000000, 0.47), (2000000, 0.6), (5000000, 0.87), (10000000, 1.1), (50000000, 1.3)] },
    Row { family: "minmax_int", keys: "2+", key_class: "i64", source: "memory", bucket: "10k", min_rows: None, max_rows: None, ratios: &[(1000000, 0.76), (2000000, 0.89), (5000000, 1.0), (10000000, 1.1), (50000000, 1.1)] },
    Row { family: "minmax_int", keys: "2+", key_class: "i64", source: "memory", bucket: "100k", min_rows: None, max_rows: None, ratios: &[(1000000, 1.1), (2000000, 1.7), (5000000, 2.0), (10000000, 2.1), (50000000, 2.1)] }, // first run after idle below DataFusion alone at every size
    Row { family: "minmax_int", keys: "2+", key_class: "i64", source: "memory", bucket: "1M", min_rows: None, max_rows: None, ratios: &[(5000000, 1.6), (10000000, 1.8), (50000000, 1.8)] }, // first run after idle below DataFusion alone at every size
    Row { family: "minmax_int", keys: "2+", key_class: "i64", source: "memory", bucket: "rows/2", min_rows: None, max_rows: None, ratios: &[(1000000, 1.4), (2000000, 1.6), (5000000, 1.4), (10000000, 1.2), (50000000, 0.58)] },
    Row { family: "sum_avg_f64", keys: "1", key_class: "i32", source: "memory", bucket: "200", min_rows: None, max_rows: None, ratios: &[(1000000, 0.22), (2000000, 0.43), (5000000, 0.56), (10000000, 0.62), (50000000, 0.68)] },
    Row { family: "sum_avg_f64", keys: "1", key_class: "i32", source: "memory", bucket: "10k", min_rows: None, max_rows: None, ratios: &[(1000000, 0.47), (2000000, 0.46), (5000000, 0.55), (10000000, 0.49), (50000000, 0.46)] },
    Row { family: "sum_avg_f64", keys: "1", key_class: "i32", source: "memory", bucket: "100k", min_rows: None, max_rows: None, ratios: &[(1000000, 0.78), (2000000, 1.0), (5000000, 1.0), (10000000, 1.0), (50000000, 0.77)] },
    Row { family: "sum_avg_f64", keys: "1", key_class: "i32", source: "memory", bucket: "1M", min_rows: None, max_rows: None, ratios: &[(5000000, 0.75), (10000000, 0.87), (50000000, 0.92)] },
    Row { family: "sum_avg_f64", keys: "1", key_class: "i32", source: "memory", bucket: "rows/2", min_rows: None, max_rows: None, ratios: &[(1000000, 0.52), (2000000, 0.61), (5000000, 0.53), (10000000, 0.55), (50000000, 0.44)] },
    Row { family: "sum_avg_f64", keys: "1", key_class: "i64", source: "memory", bucket: "200", min_rows: None, max_rows: None, ratios: &[(1000000, 0.31), (2000000, 0.4), (5000000, 0.51), (10000000, 0.57), (50000000, 0.64)] },
    Row { family: "sum_avg_f64", keys: "1", key_class: "i64", source: "memory", bucket: "10k", min_rows: None, max_rows: None, ratios: &[(1000000, 0.47), (2000000, 0.48), (5000000, 0.57), (10000000, 0.48), (50000000, 0.46)] },
    Row { family: "sum_avg_f64", keys: "1", key_class: "i64", source: "memory", bucket: "100k", min_rows: None, max_rows: None, ratios: &[(1000000, 0.81), (2000000, 0.94), (5000000, 1.0), (10000000, 1.0), (50000000, 0.84)] },
    Row { family: "sum_avg_f64", keys: "1", key_class: "i64", source: "memory", bucket: "1M", min_rows: None, max_rows: None, ratios: &[(5000000, 0.75), (10000000, 0.94), (50000000, 1.0)] },
    Row { family: "sum_avg_f64", keys: "1", key_class: "i64", source: "memory", bucket: "rows/2", min_rows: None, max_rows: None, ratios: &[(1000000, 0.54), (2000000, 0.63), (5000000, 0.54), (10000000, 0.58), (50000000, 0.45)] },
    Row { family: "sum_avg_f64", keys: "2+", key_class: "i32", source: "memory", bucket: "200", min_rows: None, max_rows: None, ratios: &[(1000000, 0.43), (2000000, 0.59), (5000000, 0.96), (10000000, 1.1), (50000000, 1.1)] },
    Row { family: "sum_avg_f64", keys: "2+", key_class: "i32", source: "memory", bucket: "10k", min_rows: None, max_rows: None, ratios: &[(1000000, 0.54), (2000000, 0.75), (5000000, 0.82), (10000000, 0.85), (50000000, 0.75)] },
    Row { family: "sum_avg_f64", keys: "2+", key_class: "i32", source: "memory", bucket: "100k", min_rows: None, max_rows: None, ratios: &[(1000000, 0.79), (2000000, 1.0), (5000000, 1.1), (10000000, 1.3), (50000000, 1.2)] },
    Row { family: "sum_avg_f64", keys: "2+", key_class: "i32", source: "memory", bucket: "1M", min_rows: None, max_rows: None, ratios: &[(5000000, 0.84), (10000000, 1.0), (50000000, 1.2)] },
    Row { family: "sum_avg_f64", keys: "2+", key_class: "i32", source: "memory", bucket: "rows/2", min_rows: None, max_rows: None, ratios: &[(1000000, 0.61), (2000000, 0.68), (5000000, 0.58), (10000000, 0.66), (50000000, 0.47)] },
    Row { family: "sum_avg_f64", keys: "2+", key_class: "i64", source: "memory", bucket: "200", min_rows: None, max_rows: None, ratios: &[(1000000, 0.44), (2000000, 0.57), (5000000, 0.79), (10000000, 1.0), (50000000, 0.98)] },
    Row { family: "sum_avg_f64", keys: "2+", key_class: "i64", source: "memory", bucket: "10k", min_rows: None, max_rows: None, ratios: &[(1000000, 0.59), (2000000, 0.73), (5000000, 0.77), (10000000, 0.82), (50000000, 0.81)] },
    Row { family: "sum_avg_f64", keys: "2+", key_class: "i64", source: "memory", bucket: "100k", min_rows: None, max_rows: None, ratios: &[(1000000, 0.85), (2000000, 1.1), (5000000, 1.2), (10000000, 1.4), (50000000, 1.4)] },
    Row { family: "sum_avg_f64", keys: "2+", key_class: "i64", source: "memory", bucket: "1M", min_rows: None, max_rows: None, ratios: &[(5000000, 0.9), (10000000, 1.1), (50000000, 1.4)] },
    Row { family: "sum_avg_f64", keys: "2+", key_class: "i64", source: "memory", bucket: "rows/2", min_rows: None, max_rows: None, ratios: &[(1000000, 0.62), (2000000, 0.7), (5000000, 0.64), (10000000, 0.71), (50000000, 0.49)] },
    Row { family: "sum_avg_int", keys: "1", key_class: "i32", source: "memory", bucket: "200", min_rows: None, max_rows: None, ratios: &[(1000000, 0.37), (2000000, 0.51), (5000000, 0.64), (10000000, 0.69), (50000000, 1.1)] },
    Row { family: "sum_avg_int", keys: "1", key_class: "i32", source: "memory", bucket: "10k", min_rows: None, max_rows: None, ratios: &[(1000000, 0.58), (2000000, 0.66), (5000000, 0.93), (10000000, 0.86), (50000000, 0.96)] },
    Row { family: "sum_avg_int", keys: "1", key_class: "i32", source: "memory", bucket: "100k", min_rows: None, max_rows: None, ratios: &[(1000000, 0.98), (2000000, 1.5), (5000000, 2.1), (10000000, 1.6), (50000000, 1.5)] },
    Row { family: "sum_avg_int", keys: "1", key_class: "i32", source: "memory", bucket: "1M", min_rows: None, max_rows: None, ratios: &[(5000000, 1.3), (10000000, 1.6), (50000000, 2.1)] },
    Row { family: "sum_avg_int", keys: "1", key_class: "i32", source: "memory", bucket: "rows/2", min_rows: None, max_rows: None, ratios: &[(1000000, 0.95), (2000000, 1.1), (5000000, 1.0), (10000000, 1.0), (50000000, 0.63)] },
    Row { family: "sum_avg_int", keys: "1", key_class: "i64", source: "memory", bucket: "200", min_rows: None, max_rows: None, ratios: &[(1000000, 0.35), (2000000, 0.45), (5000000, 0.64), (10000000, 0.73), (50000000, 0.9)] },
    Row { family: "sum_avg_int", keys: "1", key_class: "i64", source: "memory", bucket: "10k", min_rows: None, max_rows: None, ratios: &[(1000000, 0.58), (2000000, 0.66), (5000000, 0.82), (10000000, 0.81), (50000000, 0.94)] },
    Row { family: "sum_avg_int", keys: "1", key_class: "i64", source: "memory", bucket: "100k", min_rows: None, max_rows: None, ratios: &[(1000000, 0.88), (2000000, 1.2), (5000000, 1.7), (10000000, 1.6), (50000000, 1.6)] },
    Row { family: "sum_avg_int", keys: "1", key_class: "i64", source: "memory", bucket: "1M", min_rows: None, max_rows: None, ratios: &[(5000000, 1.3), (10000000, 1.6), (50000000, 2.0)] },
    Row { family: "sum_avg_int", keys: "1", key_class: "i64", source: "memory", bucket: "rows/2", min_rows: None, max_rows: None, ratios: &[(1000000, 0.89), (2000000, 1.1), (5000000, 1.0), (10000000, 1.1), (50000000, 0.66)] },
    Row { family: "sum_avg_int", keys: "2+", key_class: "i32", source: "memory", bucket: "200", min_rows: None, max_rows: None, ratios: &[(1000000, 0.51), (2000000, 0.72), (5000000, 1.2), (10000000, 1.3), (50000000, 1.5)] },
    Row { family: "sum_avg_int", keys: "2+", key_class: "i32", source: "memory", bucket: "10k", min_rows: None, max_rows: None, ratios: &[(1000000, 0.69), (2000000, 0.89), (5000000, 1.2), (10000000, 1.3), (50000000, 1.5)] },
    Row { family: "sum_avg_int", keys: "2+", key_class: "i32", source: "memory", bucket: "100k", min_rows: None, max_rows: None, ratios: &[(1000000, 0.96), (2000000, 1.6), (5000000, 1.9), (10000000, 2.1), (50000000, 2.3)] }, // first run after idle below DataFusion alone at every size
    Row { family: "sum_avg_int", keys: "2+", key_class: "i32", source: "memory", bucket: "1M", min_rows: None, max_rows: None, ratios: &[(5000000, 1.4), (10000000, 1.8), (50000000, 2.4)] }, // first run after idle below DataFusion alone at every size
    Row { family: "sum_avg_int", keys: "2+", key_class: "i32", source: "memory", bucket: "rows/2", min_rows: None, max_rows: None, ratios: &[(1000000, 0.94), (2000000, 1.1), (5000000, 1.2), (10000000, 1.2), (50000000, 0.66)] },
    Row { family: "sum_avg_int", keys: "2+", key_class: "i64", source: "memory", bucket: "200", min_rows: None, max_rows: None, ratios: &[(1000000, 0.49), (2000000, 0.65), (5000000, 0.92), (10000000, 1.1), (50000000, 1.4)] },
    Row { family: "sum_avg_int", keys: "2+", key_class: "i64", source: "memory", bucket: "10k", min_rows: None, max_rows: None, ratios: &[(1000000, 0.7), (2000000, 0.81), (5000000, 1.1), (10000000, 1.2), (50000000, 1.6)] },
    Row { family: "sum_avg_int", keys: "2+", key_class: "i64", source: "memory", bucket: "100k", min_rows: None, max_rows: None, ratios: &[(1000000, 0.99), (2000000, 1.5), (5000000, 1.8), (10000000, 2.1), (50000000, 2.4)] }, // first run after idle below DataFusion alone at every size
    Row { family: "sum_avg_int", keys: "2+", key_class: "i64", source: "memory", bucket: "1M", min_rows: None, max_rows: None, ratios: &[(5000000, 1.5), (10000000, 1.9), (50000000, 2.6)] }, // first run after idle below DataFusion alone at every size
    Row { family: "sum_avg_int", keys: "2+", key_class: "i64", source: "memory", bucket: "rows/2", min_rows: None, max_rows: None, ratios: &[(1000000, 0.98), (2000000, 1.1), (5000000, 1.2), (10000000, 1.2), (50000000, 0.68)] },
];
