// Generated by Benchmarks/router_table.py from Benchmarks/results/router_2026-09-17.json and
// Benchmarks/results/crossover_bench_2026-09-17.csv. Do not edit by hand: rerun the script.
// Bench header: ArrowMetal crossover on Apple M4 Max, 16 CPU cores, best of up to 20 (5 at 10M rows and above), 10% nulls, 2026-09-17T03:16:33Z
//
// The CPU side of these timings is the bench's own single-core loops in
// Sources/ArrowMetalBench/main.swift (`cpu-1core`; `cpu-candidate` for the group-by), measured
// before Sources/ArrowMetal/Router/RouterCPU.swift existed, not the RouterCPU loops the router
// runs. Regenerate from a quiet run of the shipped loops with
// `Benchmarks/router_table.py --from-check Benchmarks/results/router_check_<date>.csv`.
//
// The multiply row comes from Benchmarks/results/router_check_2026-09-23_provisional.csv,
// since the sweep above timed add only. Its CPU side is the shipped RouterCPU multiply loop,
// timed by Benchmarks/router_check.py. Check header: ArrowMetal router check on Apple M4 Max, 16 CPU cores, Apple M4 Max, best of 20 (5 at 3M rows and above), int64 with 10% nulls, Python binding on resident arrays, 2026-09-24T05:01:47Z; provisional: other build lanes were running on this machine and GPU

/// The router's crossover table: per routed operation, the row count from which the GPU path
/// was measured at least as fast as a single-core CPU loop of the 2026-09-17 bench (not the RouterCPU loops; see the header).
/// Measured on int64 columns with 10% nulls; docs/DESIGN.md (CPU/GPU router) says how the table
/// is used.
enum RouterTable {
    /// Results file the table was generated from.
    static let source = "Benchmarks/results/router_2026-09-17.json"

    /// Fitted crossover in rows (straight lines between the two bracketing measured sizes).
    static func crossoverRows(_ op: RoutedOp) -> Int {
        switch op {
        case .sum: return 176850   // sum(int64); 100,000 rows: GPU 129.9 us, CPU 61 us; 1,000,000 rows: GPU 223.5 us, CPU 961.5 us
        case .min: return 334407   // min(int64); 100,000 rows: GPU 129.8 us, CPU 45.7 us; 1,000,000 rows: GPU 263.8 us, CPU 502.6 us
        case .max: return 337053   // max(int64); 100,000 rows: GPU 123.1 us, CPU 40 us; 1,000,000 rows: GPU 259.8 us, CPU 492.2 us
        case .compare: return 1026915   // compare(int64 > 0); 1,000,000 rows: GPU 144 us, CPU 140.9 us; 10,000,000 rows: GPU 526 us, CPU 1559.5 us
        case .arithmetic: return 1724452   // add(int64, 1); 1,000,000 rows: GPU 189.6 us, CPU 118 us; 10,000,000 rows: GPU 490.5 us, CPU 1308.4 us
        case .filter: return 612734   // filter(int64, mask); 100,000 rows: GPU 372.4 us, CPU 27.9 us; 1,000,000 rows: GPU 426 us, CPU 686.2 us
        case .groupBySum: return 269711   // group-by sum (1000 keys); 100,000 rows: GPU 214.7 us, CPU 103.2 us; 1,000,000 rows: GPU 563.5 us, CPU 1043.3 us
        }
    }

    /// First measured size from which the GPU stayed ahead (the step).
    static func measuredStepRows(_ op: RoutedOp) -> Int {
        switch op {
        case .sum: return 1000000
        case .min: return 1000000
        case .max: return 1000000
        case .compare: return 10000000
        case .arithmetic: return 10000000
        case .filter: return 1000000
        case .groupBySum: return 1000000
        }
    }

    /// Largest measured size below the step (the CPU was measured ahead there).
    static func bracketLowRows(_ op: RoutedOp) -> Int {
        switch op {
        case .sum: return 100000
        case .min: return 100000
        case .max: return 100000
        case .compare: return 1000000
        case .arithmetic: return 1000000
        case .filter: return 100000
        case .groupBySum: return 100000
        }
    }

    /// Results file the multiply row was fitted from (a router_check.py CSV).
    static let multiplySource = "Benchmarks/results/router_check_2026-09-23_provisional.csv"

    /// `multiply`'s own crossover: the arithmetic row above was measured on add (subtract follows it).
    static let multiplyCrossoverRows = 525060   // multiply(int64, 3); 300,000 rows: GPU 122.8 us, CPU 82 us; 1,000,000 rows: GPU 180.1 us, CPU 266.2 us
    static let multiplyMeasuredStepRows = 1000000
    static let multiplyBracketLowRows = 300000
}
