// Generated by Benchmarks/router_table.py from Benchmarks/results/router_check_2026-09-24.csv.
// Do not edit by hand: rerun the script.
// Check header: ArrowMetal router check on Apple M4 Max, 16 CPU cores, Apple M4 Max, best of 20 (5 at 3M rows and above), int64 with 10% nulls, Python binding on resident arrays, 2026-09-24T17:58:16Z
//
// The CPU side of these timings is the shipped RouterCPU loops, timed by
// Benchmarks/router_check.py with the router pinned to `cpu`, against the GPU pinned to `gpu`.

/// The router's crossover table: per routed operation, the row count from which the GPU path
/// was measured at least as fast as the router's single-core CPU loop (RouterCPU), as timed by Benchmarks/router_check.py.
/// Measured on int64 columns with 10% nulls; docs/DESIGN.md (CPU/GPU router) says how the table
/// is used.
enum RouterTable {
    /// Results file the table was generated from.
    static let source = "Benchmarks/results/router_check_2026-09-24.csv"

    /// Fitted crossover in rows (straight lines between the two bracketing measured sizes).
    static func crossoverRows(_ op: RoutedOp) -> Int {
        switch op {
        case .sum: return 220881   // sum(int64); 100,000 rows: GPU 125.6 us, CPU 46 us; 300,000 rows: GPU 161.5 us, CPU 213.6 us
        case .min: return 234408   // min(int64); 100,000 rows: GPU 124.2 us, CPU 65.8 us; 300,000 rows: GPU 180.3 us, CPU 208.8 us
        case .max: return 227546   // max(int64); 100,000 rows: GPU 126.3 us, CPU 66.8 us; 300,000 rows: GPU 178.4 us, CPU 212.2 us
        case .compare: return 2668823   // compare(int64 > 0); 1,000,000 rows: GPU 141.5 us, CPU 77 us; 3,000,000 rows: GPU 211.2 us, CPU 224 us
        case .arithmetic: return 1629041   // add(int64, 1); 1,000,000 rows: GPU 181.8 us, CPU 120.5 us; 3,000,000 rows: GPU 230.1 us, CPU 363.7 us
        case .filter: return 591365   // filter(int64, mask); 300,000 rows: GPU 375 us, CPU 198.1 us; 1,000,000 rows: GPU 406.8 us, CPU 654.9 us
        case .groupBySum: return 716029   // group-by sum (1000 keys); 300,000 rows: GPU 269.9 us, CPU 186.1 us; 1,000,000 rows: GPU 558 us, CPU 615.2 us
        }
    }

    /// First measured size from which the GPU stayed ahead (the step).
    static func measuredStepRows(_ op: RoutedOp) -> Int {
        switch op {
        case .sum: return 300000
        case .min: return 300000
        case .max: return 300000
        case .compare: return 3000000
        case .arithmetic: return 3000000
        case .filter: return 1000000
        case .groupBySum: return 1000000
        }
    }

    /// Largest measured size below the step (the CPU was measured ahead there).
    static func bracketLowRows(_ op: RoutedOp) -> Int {
        switch op {
        case .sum: return 100000
        case .min: return 100000
        case .max: return 100000
        case .compare: return 1000000
        case .arithmetic: return 1000000
        case .filter: return 300000
        case .groupBySum: return 300000
        }
    }

    /// Results file the multiply row was fitted from (a router_check.py CSV).
    static let multiplySource = "Benchmarks/results/router_check_2026-09-24.csv"

    /// `multiply`'s own crossover: the arithmetic row above was measured on add (subtract follows it).
    static let multiplyCrossoverRows = 678287   // multiply(int64, 3); 300,000 rows: GPU 126.7 us, CPU 71.2 us; 1,000,000 rows: GPU 185 us, CPU 232.2 us
    static let multiplyMeasuredStepRows = 1000000
    static let multiplyBracketLowRows = 300000
}
