import Foundation

// The crossover table the router reads, as a value: the shipped one (RouterTable.swift, generated by
// Benchmarks/router_table.py) or a per-machine one written by `python -m arrowmetal.router calibrate`
// (the JSON format below, also written by `router_table.py --json-out`). docs/CROSSOVER.md has the
// pipeline.
//
// JSON format "arrowmetal-router-table/1" (the fields the router reads; writers add more):
//
//     {"format": "arrowmetal-router-table/1",
//      "machine": {"chip": "Apple M4 Max", "cpu_cores": 16, ...},
//      "date": "2026-09-25T10:00:00Z", "arrowmetal_version": "0.2.0", "grid": {"name": "quick", ...},
//      "source": "...", "header": "...",
//      "crossovers": {"sum": {"label": "sum(int64)", "crossover_rows": 220881, "step_rows": 300000,
//                             "bracket_low_rows": 100000,
//                             "points": [{"rows": 100000, "gpu_us": 125.6, "cpu_us": 46.0}, ...]},
//                     "min": ..., "max": ..., "compare": ..., "arithmetic": ..., "filter": ...,
//                     "group_by_sum": ..., "multiply": ...}}
//
// An operation whose entry is missing or has "crossover_rows": null (the sweep did not reach a
// crossover inside its grid) keeps the shipped row, and `shippedOps` names it.

/// One measured point behind a crossover: GPU and CPU wall microseconds at `rows`.
public struct RouterPoint: Equatable, Sendable {
    public let rows: Int
    public let gpuMicros: Double
    public let cpuMicros: Double
}

/// One row of the crossover table.
public struct RouterRow: Equatable, Sendable {
    /// The benchmark case the row was fitted from ("sum(int64)").
    public let label: String
    /// Below this many rows `auto` runs the CPU loop.
    public let crossover: Int
    /// First measured size from which the GPU stayed ahead.
    public let stepRows: Int
    /// Largest measured size below the step.
    public let bracketLowRows: Int
    /// The two measured points the crossover was fitted between (empty when the CPU was never ahead).
    public let points: [RouterPoint]
}

/// A complete crossover table: one row per routed operation plus multiply's own row.
public struct RouterCrossovers: Equatable, Sendable {
    public enum Origin: Equatable, Sendable {
        /// The table compiled into the library (RouterTable.swift).
        case shipped
        /// A JSON table loaded from this path.
        case file(String)
    }

    public let origin: Origin
    public let rows: [RoutedOp: RouterRow]
    public let multiply: RouterRow
    /// Results file or command the table came from.
    public let source: String
    /// Machine and protocol line of the measurement.
    public let header: String
    /// Chip the table was measured on, when the file says.
    public let chip: String?
    /// Measurement date, when the file says.
    public let date: String?
    /// Name of the size grid that ran (`quick`, `full`), when the file says.
    public let grid: String?
    /// Operations whose row was not in the file and come from the shipped table.
    public let shippedOps: [String]

    public var isShipped: Bool { origin == .shipped }

    /// The crossover for `op` (for `.arithmetic`, the add/subtract row).
    @inline(__always) public func crossover(_ op: RoutedOp) -> Int { rows[op]!.crossover }

    /// The crossover for one arithmetic operation: multiply has its own row, divide is not routed.
    public func crossover(arithmetic op: ArithmeticOp) -> Int? {
        switch op {
        case .add, .sub: return crossover(.arithmetic)
        case .mul: return multiply.crossover
        case .div: return nil
        }
    }

    // MARK: the shipped table

    public static let shipped: RouterCrossovers = {
        func row(_ op: RoutedOp) -> RouterRow {
            RouterRow(label: RouterTable.label(op), crossover: RouterTable.crossoverRows(op),
                      stepRows: RouterTable.measuredStepRows(op), bracketLowRows: RouterTable.bracketLowRows(op),
                      points: RouterTable.bracketPoints(op).map { RouterPoint(rows: $0.0, gpuMicros: $0.1, cpuMicros: $0.2) })
        }
        var rows: [RoutedOp: RouterRow] = [:]
        for op in RoutedOp.allCases { rows[op] = row(op) }
        let mul = RouterRow(label: RouterTable.multiplyLabel, crossover: RouterTable.multiplyCrossoverRows,
                            stepRows: RouterTable.multiplyMeasuredStepRows, bracketLowRows: RouterTable.multiplyBracketLowRows,
                            points: RouterTable.multiplyBracketPoints.map { RouterPoint(rows: $0.0, gpuMicros: $0.1, cpuMicros: $0.2) })
        return RouterCrossovers(origin: .shipped, rows: rows, multiply: mul, source: RouterTable.source,
                                header: RouterTable.header, chip: nil, date: nil, grid: nil, shippedOps: [])
    }()

    // MARK: JSON

    public static let format = "arrowmetal-router-table/1"

    public struct LoadError: Error, CustomStringConvertible {
        public let description: String
    }

    /// Reads a table in the JSON format above.
    public static func load(path: String) throws -> RouterCrossovers {
        let data: Data
        do { data = try Data(contentsOf: URL(fileURLWithPath: path)) } catch {
            throw LoadError(description: "router table \(path): cannot read (\(error.localizedDescription))")
        }
        return try parse(data, origin: .file(path))
    }

    /// Parses a table in the JSON format above; `origin` is recorded as given.
    public static func parse(_ data: Data, origin: Origin) throws -> RouterCrossovers {
        let name: String
        if case .file(let p) = origin { name = p } else { name = "shipped" }
        func fail(_ why: String) -> LoadError { LoadError(description: "router table \(name): \(why)") }
        guard let obj = (try? JSONSerialization.jsonObject(with: data)) as? [String: Any] else { throw fail("not a JSON object") }
        guard let fmt = obj["format"] as? String, fmt == format else {
            throw fail("format is \(obj["format"].map { "\($0)" } ?? "missing"), expected \(format)")
        }
        guard let entries = obj["crossovers"] as? [String: Any] else { throw fail("no \"crossovers\" object") }
        func int(_ v: Any?) -> Int? {
            if let n = v as? NSNumber, CFGetTypeID(n) != CFBooleanGetTypeID() {
                let d = n.doubleValue
                return d == d.rounded() && d >= 1 && d < 9.0e18 ? Int(d) : nil
            }
            return nil
        }
        func row(_ key: String, fallback: RouterRow) throws -> RouterRow? {
            guard let raw = entries[key], !(raw is NSNull) else { return nil }
            guard let e = raw as? [String: Any] else { throw fail("\"\(key)\" is not an object") }
            if e["crossover_rows"] == nil || e["crossover_rows"] is NSNull { return nil }
            guard let c = int(e["crossover_rows"]) else { throw fail("\"\(key)\".crossover_rows is not a positive integer") }
            let pts: [RouterPoint] = ((e["points"] as? [[String: Any]]) ?? []).compactMap { p in
                guard let n = int(p["rows"]), let g = (p["gpu_us"] as? NSNumber)?.doubleValue,
                      let cpu = (p["cpu_us"] as? NSNumber)?.doubleValue else { return nil }
                return RouterPoint(rows: n, gpuMicros: g, cpuMicros: cpu)
            }
            return RouterRow(label: (e["label"] as? String) ?? fallback.label, crossover: c,
                             stepRows: int(e["step_rows"]) ?? c, bracketLowRows: int(e["bracket_low_rows"]) ?? c,
                             points: pts)
        }
        let known = Set(RoutedOp.allCases.map(\.rawValue) + ["multiply"])
        if let unknown = entries.keys.filter({ !known.contains($0) }).sorted().first {
            throw fail("unknown operation \"\(unknown)\"")
        }
        var rows: [RoutedOp: RouterRow] = [:]
        var fromShipped: [String] = []
        for op in RoutedOp.allCases {
            if let r = try row(op.rawValue, fallback: shipped.rows[op]!) { rows[op] = r } else {
                rows[op] = shipped.rows[op]!; fromShipped.append(op.rawValue)
            }
        }
        var mul = shipped.multiply
        if let r = try row("multiply", fallback: shipped.multiply) { mul = r } else { fromShipped.append("multiply") }
        if fromShipped.count == RoutedOp.allCases.count + 1 { throw fail("no operation has a crossover") }
        let machine = obj["machine"] as? [String: Any]
        let grid = obj["grid"] as? [String: Any]
        return RouterCrossovers(origin: origin, rows: rows, multiply: mul,
                                source: (obj["source"] as? String) ?? name, header: (obj["header"] as? String) ?? "",
                                chip: machine?["chip"] as? String, date: obj["date"] as? String,
                                grid: grid?["name"] as? String, shippedOps: fromShipped)
    }

    // MARK: which table at load

    /// "Apple M4 Max" -> "apple-m4-max": the file name of this chip's table.
    public static func chipID(_ chip: String) -> String {
        var out = ""
        var dash = false
        for ch in chip.lowercased().unicodeScalars {
            if CharacterSet.alphanumerics.contains(ch) && ch.isASCII { out.unicodeScalars.append(ch); dash = false }
            else if !out.isEmpty && !dash { out.append("-"); dash = true }
        }
        while out.hasSuffix("-") { out.removeLast() }
        return out.isEmpty ? "unknown" : out
    }

    /// `sysctl machdep.cpu.brand_string`, the chip the per-machine table is named after.
    public static var machineChip: String {
        var size = 0
        guard sysctlbyname("machdep.cpu.brand_string", nil, &size, nil, 0) == 0, size > 0 else { return "unknown" }
        var buf = [CChar](repeating: 0, count: size)
        guard sysctlbyname("machdep.cpu.brand_string", &buf, &size, nil, 0) == 0 else { return "unknown" }
        return String(cString: buf)
    }

    /// `~/.arrowmetal/router/<chip id>.json` for `home` and `chip`.
    public static func machineTablePath(home: String, chip: String) -> String {
        (home as NSString).appendingPathComponent(".arrowmetal/router/\(chipID(chip)).json")
    }

    /// The table the router starts with, and an error when a named table could not be read:
    /// `ARROWMETAL_ROUTER_TABLE=<path>` loads that file, `ARROWMETAL_ROUTER_TABLE=shipped` keeps the
    /// shipped table, and otherwise `~/.arrowmetal/router/<chip id>.json` is loaded when it exists. A
    /// file that does not parse leaves the shipped table in force; the error says why.
    public static func initial(environment: [String: String], home: String?, chip: String) -> (RouterCrossovers, String?) {
        if let v = environment["ARROWMETAL_ROUTER_TABLE"], !v.isEmpty {
            if v.lowercased() == "shipped" { return (shipped, nil) }
            do { return (try load(path: v), nil) } catch { return (shipped, "\(error)") }
        }
        guard let home, !home.isEmpty else { return (shipped, nil) }
        let path = machineTablePath(home: home, chip: chip)
        guard FileManager.default.fileExists(atPath: path) else { return (shipped, nil) }
        do { return (try load(path: path), nil) } catch { return (shipped, "\(error)") }
    }
}
