/* Generated by configure. The absolute path of the dylib found next to the package source at
   install time, or the empty string when there was none. */
#define ARROWMETAL_DEFAULT_LIB "/Users/aiexplore369/Documents/ai_coding/appleunifiedarrrowframework/.build/release/libArrowMetalC.dylib"
