#!/usr/bin/env python3
"""The differential matrix, counted per Apache Arrow compute function: the generated table in
docs/COVERAGE.md and the per-section summary in docs/ARROW_FUNCTIONS.md.

    PYTHONPATH=python python python/tests/coverage_report.py            # run the matrix, write both pages
    PYTHONPATH=python python python/tests/coverage_report.py --check    # run the matrix, compare, write nothing
    PYTHONPATH=python python python/tests/coverage_report.py --render   # rewrite the pages from the recorded run

A run is the default matrix of `test_differential.py` (the one `differential_report.py` prints, no
DIFF_QUICK, no DIFF_LARGE, the router pinned to the GPU). Its per-cell counts -- one cell per
(operation, column type), each run over every dataset -- are recorded in RECORD, and both pages are
rendered from that file, so no number on them is typed by hand. `differential_report.py` compares
every full run with RECORD and exits 3 when they differ; `test_coverage_report.py` checks that the
pages equal a rendering of RECORD, that RECORD has exactly the matrix's cells, and reruns a seeded
sample of cells against it.

Which Arrow function a case counts toward is the table OPERATION_FUNCTIONS below: the Arrow function
whose ArrowMetal implementation the operation calls (the call column of ARROW_FUNCTIONS.md) or, for an
ArrowMetal call with no Arrow name of its own (`sort`, `argsort`, `to_strings`, ...), the Arrow
function its answer is compared with. Operations that check no Arrow function -- interop, slicing,
ArrowMetal's own hashes and window functions -- are in OUTSIDE with what they check instead.
"""
import argparse
import json
import os
import sys
from collections import OrderedDict

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, HERE)

RECORD = os.path.join(ROOT, "docs", "data", "differential_coverage.json")
COVERAGE_MD = os.path.join(ROOT, "docs", "COVERAGE.md")
ARROW_FUNCTIONS_MD = os.path.join(ROOT, "docs", "ARROW_FUNCTIONS.md")
BEGIN = "<!-- BEGIN differential cases per function: generated by python/tests/coverage_report.py -->"
END = "<!-- END differential cases per function -->"
COMMAND = "PYTHONPATH=python python python/tests/coverage_report.py"

_CMP = ("equal", "not_equal", "less", "less_equal", "greater", "greater_equal")
_ARITH = ("add", "subtract", "multiply", "divide")
_CALENDAR = ("year", "month", "day", "day_of_year", "quarter", "iso_week", "iso_year", "us_week",
             "us_year", "is_leap_year")
_CLOCK = ("hour", "minute", "second", "millisecond", "microsecond", "nanosecond", "subsecond")
_ROUND_TEMPORAL = ("floor_temporal", "ceil_temporal", "round_temporal")
_BETWEEN_CLOCK = ("hours_between", "minutes_between", "seconds_between", "milliseconds_between",
                  "microseconds_between", "nanoseconds_between")
_TRIG = ("sin", "cos", "tan", "asin", "acos", "atan", "sinh", "cosh", "tanh", "asinh", "acosh", "atanh")

#: Differential operation -> the Arrow compute functions its cases count toward (names as in
#: `arrowmetal.functions`, which has one row per Arrow name).
OPERATION_FUNCTIONS = {
    "sum": ("sum",),
    "min_max": ("min", "max"),
    "mean": ("mean",),
    "compare_scalar": _CMP,
    "compare_array": _CMP,
    "arith_scalar": _ARITH,
    "arith_array": _ARITH,
    "cast": ("cast",),
    "bool_logic": ("and_", "or_", "invert"),
    "filter": ("filter",),
    "filter_where": ("filter",) + _CMP,
    "take": ("take",),
    "sort": ("array_sort_indices",),
    "argsort": ("array_sort_indices",),
    "top_k": ("array_sort_indices",),
    "argsort_nulls_first": ("array_sort_indices",),
    "top_k_nulls_first": ("array_sort_indices",),
    "argsort_total_order": ("array_sort_indices",),
    "str_length": ("utf8_length", "binary_length"),
    "str_match": ("starts_with", "ends_with", "match_substring", "equal"),
    "str_equals_array": ("equal",),
    "dictionary_encode": ("dictionary_encode",),
    "group_by_count": ("hash_count_all",),
    "group_by_count_values": ("hash_count",),
    "group_by_sum": ("hash_sum",),
    "group_by_min": ("hash_min",),
    "group_by_max": ("hash_max",),
    "group_by_mean": ("hash_mean",),
    "group_by_sum_correctly_rounded": ("hash_sum",),
    "group_by_mean_correctly_rounded": ("hash_mean",),
    "is_null": ("is_null",),
    "is_valid": ("is_valid",),
    "is_nan": ("is_nan",),
    "abs": ("abs",),
    "negate": ("negate",),
    "sign": ("sign",),
    "upper": ("utf8_upper",),
    "lower": ("utf8_lower",),
    "trim": ("utf8_trim_whitespace",),
    "bitwise_not": ("bit_wise_not",),
    "cumulative_sum": ("cumulative_sum",),
    "cumulative_prod": ("cumulative_prod",),
    "cumulative_max": ("cumulative_max",),
    "cumulative_min": ("cumulative_min",),
    "bitwise_and": ("bit_wise_and",),
    "bitwise_or": ("bit_wise_or",),
    "bitwise_xor": ("bit_wise_xor",),
    "shift_left": ("shift_left",),
    "shift_right": ("shift_right",),
    "fill_null": ("fill_null",),
    "if_else": ("if_else",),
    "is_in": ("is_in",),
    "index_in": ("index_in",),
    "drop_null": ("drop_null",),
    "kleene": ("and_kleene", "or_kleene"),
    "rounding": ("floor", "ceil", "trunc", "round"),
    "sqrt": ("sqrt",),
    "exp": ("exp",),
    "logarithm": ("ln", "log10", "log2"),
    "element_wise_min_max": ("min_element_wise", "max_element_wise"),
    "power": ("power",),
    "ascii_upper": ("ascii_upper",),
    "ascii_lower": ("ascii_lower",),
    "swapcase": ("ascii_swapcase",),
    "capitalize": ("ascii_capitalize",),
    "ltrim": ("ascii_ltrim_whitespace",),
    "rtrim": ("ascii_rtrim_whitespace",),
    "str_reverse": ("utf8_reverse",),
    "is_alnum": ("ascii_is_alnum",),
    "is_alpha": ("ascii_is_alpha",),
    "is_digit": ("ascii_is_decimal",),
    "is_space": ("ascii_is_space",),
    "is_upper": ("ascii_is_upper",),
    "is_lower": ("ascii_is_lower",),
    "replace": ("replace_substring",),
    "repeat": ("binary_repeat",),
    "slice_codeunits": ("utf8_slice_codeunits",),
    "pad": ("utf8_lpad", "utf8_rpad"),
    "substring_search": ("count_substring", "find_substring"),
    "str_concat": ("binary_join_element_wise",),
    "dictionary_decode": ("dictionary_decode",),
    "filter_ext": ("filter",),
    "take_ext": ("take",),
    "run_end": ("run_end_decode", "run_end_encode", "filter", "take"),
    "decimal_compare": _CMP,
    "decimal_arith": ("add", "subtract", "multiply"),
    "decimal_unary": ("abs", "negate", "sign"),
    "decimal_round": ("round",),
    "decimal_to_float64": ("cast",),
    "decimal_reduce": ("min", "max", "sum"),
    "decimal_widen_narrow": ("cast",),
    "list_length": ("list_value_length",),
    "list_flatten": ("list_flatten",),
    "list_element": ("list_element",),
    "list_parent_indices": ("list_parent_indices",),
    "list_slice": ("list_slice",),
    "struct_field": ("struct_field",),
    "map_lookup": ("map_lookup",),
    "binary_join": ("binary_join",),
    "regex_match": ("match_substring_regex", "count_substring_regex", "find_substring_regex"),
    "regex_replace": ("replace_substring_regex",),
    "regex_split": ("split_pattern", "split_pattern_regex"),
    "split_whitespace": ("utf8_split_whitespace",),
    "ascii_split_whitespace": ("ascii_split_whitespace",),
    "regex_extract": ("extract_regex",),
    "regex_extract_span": ("extract_regex_span",),
    "match_like": ("match_like",),
    "string_predicates": ("ascii_is_printable", "ascii_is_title", "string_is_ascii", "utf8_is_alnum",
                          "utf8_is_alpha", "utf8_is_decimal", "utf8_is_digit", "utf8_is_lower",
                          "utf8_is_numeric", "utf8_is_printable", "utf8_is_space", "utf8_is_title",
                          "utf8_is_upper"),
    "string_case_transforms": ("ascii_title", "utf8_capitalize", "utf8_title"),
    "string_pad_and_slice": ("utf8_center", "utf8_replace_slice", "binary_replace_slice"),
    "string_trim": ("utf8_trim", "utf8_ltrim", "utf8_rtrim", "utf8_trim_whitespace",
                    "utf8_ltrim_whitespace", "utf8_rtrim_whitespace"),
    "string_normalize": ("utf8_normalize",),
    "string_set_lookup": ("is_in", "index_in"),
    "to_strings": ("cast",),
    "to_strings_text": ("cast",),
    "to_strings_value": ("cast",),
    "cast_to_string": ("cast",),
    "parse_numbers": ("cast",),
    "temporal_calendar": _CALENDAR,
    "temporal_clock": _CLOCK,
    "temporal_clock_on_a_date": _CLOCK,
    "temporal_week_options": ("week", "day_of_week"),
    "temporal_struct": ("iso_calendar", "year_month_day"),
    "temporal_timezone": ("is_dst", "local_timestamp"),
    "assume_timezone": ("assume_timezone",),
    "temporal_round": _ROUND_TEMPORAL,
    "temporal_round_finer": _ROUND_TEMPORAL,
    "temporal_round_calendar": ("floor_temporal", "round_temporal"),
    "temporal_ceil_calendar": ("ceil_temporal",),
    "temporal_round_unaligned": _ROUND_TEMPORAL,
    "temporal_round_duration": _ROUND_TEMPORAL,
    "temporal_between": ("years_between", "quarters_between", "days_between") + _BETWEEN_CLOCK,
    "temporal_between_clock": _BETWEEN_CLOCK,
    "weeks_between": ("weeks_between",),
    "interval_between": ("month_day_nano_interval_between",),
    "interval_layouts": ("month_interval_between", "day_time_interval_between"),
    "add_duration": ("add",),
    "subtract_temporal": ("subtract",),
    "add_interval": ("add",),
    "strftime": ("strftime",),
    "strftime_seconds": ("strftime",),
    "strptime": ("strptime",),
    "strptime_roundtrip": ("strptime",),
    "cast_unit": ("cast",),
    "temporal_utc_semantics": _CALENDAR + _CLOCK + ("floor_temporal",),
    "ranking": ("rank",),
    "pairwise_diff": ("pairwise_diff",),
    "cumulative_mean": ("cumulative_mean",),
    "lexsort": ("sort_indices",),
    "product": ("product",),
    "variance_and_stddev": ("variance", "stddev"),
    "quantile": ("quantile", "approximate_median"),
    "mode_and_count_distinct": ("mode", "count_distinct"),
    "first_last_index_min_max": ("first", "last", "min_max", "index"),
    "any_all": ("any", "all"),
    "float16_casts": ("cast",),
    "float16_compute": ("cast", "abs", "negate"),
    "float16_reduce": ("min", "max"),
    "fixed_binary_compare": ("equal", "not_equal"),
    "dictionary_ops": ("dictionary_decode",),
    "null_column": ("filter", "take"),
    "trig": _TRIG + ("atan2",),
    "trig_checked": ("sin_checked", "cos_checked", "tan_checked", "asin_checked", "acos_checked",
                     "acosh_checked", "atanh_checked"),
    "logical_extras": ("and_not", "and_not_kleene", "xor"),
    "float_class": ("is_finite", "is_inf", "is_nan"),
    "fill_null_direction": ("fill_null_forward", "fill_null_backward"),
    "case_when": ("case_when",),
    "choose": ("choose",),
    "replace_with_mask": ("replace_with_mask",),
    "indices_nonzero": ("indices_nonzero",),
    "coalesce": ("coalesce",),
    "arith_checked": ("add_checked", "subtract_checked", "multiply_checked", "divide_checked"),
    "power_checked": ("power_checked",),
    "shift_checked": ("shift_left_checked", "shift_right_checked"),
    "unary_checked": ("abs_checked", "negate_checked"),
    "log_checked": ("ln_checked", "log10_checked", "log2_checked", "log1p_checked", "sqrt_checked"),
    "cumulative_checked": ("cumulative_sum_checked", "cumulative_prod_checked", "pairwise_diff_checked"),
    "math_extra": ("expm1", "log1p", "logb", "logb_checked", "hypot"),
    "round_extra": ("round", "round_binary", "round_to_multiple"),
    "unique": ("unique",),
    "value_counts": ("value_counts",),
    "sort_indices": ("array_sort_indices", "sort_indices"),
    "array_selection": ("array_filter", "array_take"),
    "invert": ("invert",),
    "select_k_unstable": ("select_k_unstable", "bottom_k_unstable", "top_k_unstable"),
    "partition_nth_indices": ("partition_nth_indices",),
    "permutation": ("inverse_permutation", "scatter"),
    "scatter": ("scatter",),
    "skew_kurtosis": ("skew", "kurtosis"),
    "tdigest": ("tdigest",),
    "winsorize": ("winsorize",),
    "rank_quantile_and_normal": ("rank_quantile", "rank_normal"),
    "first_last": ("first_last",),
    "true_unless_null": ("true_unless_null",),
    "list_parent_indices64": ("list_parent_indices",),
    "ascii_pad": ("ascii_lpad", "ascii_rpad", "ascii_center", "utf8_lpad", "utf8_rpad"),
    "swapcase_and_zero_fill": ("utf8_swapcase", "ascii_swapcase", "utf8_zero_fill"),
    "byte_transforms": ("binary_slice", "binary_reverse", "ascii_reverse"),
    "extract_regex_structs": ("extract_regex", "extract_regex_span"),
    "timezone_metadata": ("cast",),
}

#: Differential operations that check no Arrow compute function, and what they check instead.
OUTSIDE = {
    "roundtrip": "import and export through the Arrow C Data Interface",
    "roundtrip_ext": "import and export of the extended types through the Arrow C Data Interface",
    "slice": "zero-copy slicing (`Array.slice`, not a compute function)",
    "slice_ext": "zero-copy slicing of the extended types",
    "str_hash32": "ArrowMetal's 32-bit string hash: null positions kept, no collisions over the data",
    "hash64": "ArrowMetal's 64-bit hash: null positions kept, equal values hash equal, no collisions",
    "modulo": "integer remainder, against Arrow's `divide`, `multiply` and `subtract` (Arrow has no modulo)",
    "months_between": "whole months between two dates, against Arrow's `year` and `month` arithmetic",
    "temporal_field_types": "the result type of every temporal extractor",
    "percent_rank_and_cume_dist": "window functions, against a reference written in the harness",
    "shift": "window shift with and without a fill value, against a reference written in the harness",
    "rolling_min_max": "rolling windows, against Arrow's `min` / `max` over each window",
    "rolling_sum": "rolling windows, against Arrow's `sum` over each window",
    "rolling_mean": "rolling windows, against Arrow's `mean` over each window",
    "extension_type": "extension name, metadata and storage through the C Data Interface",
    "nulls_constructor": "`am.nulls(n)` against `pa.nulls(n)`",
    "split_pairs": "the offsets-and-values form of the splits against their list form",
}


# ---------------------------------------------------------------------------------------------------
# the record: one row per (operation, type) cell

FIELDS = ("operation", "type", "cases", "pass", "documented", "unclassified", "skipped")


def cells_from_report(cells):
    """differential_report.run()'s {(op, type): Cell} -> sorted record rows (lists, FIELDS order)."""
    rows = []
    for (op_name, type_name), c in cells.items():
        documented = c.failed - c.new
        rows.append([op_name, type_name, c.total, c.passed, documented, c.new, c.skipped])
    return sorted(rows, key=lambda r: (r[0], r[1]))


def run_conditions():
    import pyarrow as pa
    import arrowmetal as am
    return OrderedDict([("arrowmetal", am.__version__), ("pyarrow", pa.__version__),
                        ("device", am.device_name()), ("router", am.get_router())])


def default_matrix_problem():
    """Why the current process is not running the default matrix, or None."""
    for var in ("DIFF_QUICK", "DIFF_LARGE"):
        if os.environ.get(var) == "1":
            return f"{var}=1 changes the datasets; the record is the default matrix"
    router = os.environ.get("ARROWMETAL_ROUTER")
    if router not in (None, "gpu"):
        return f"ARROWMETAL_ROUTER={router}; the record is the matrix with the router pinned to the GPU"
    return None


def load_record(path=RECORD):
    with open(path) as fh:
        return json.load(fh)


def dump_record(record):
    """JSON with one cell per line, so a changed cell is a one-line diff."""
    lines = ["{", '  "run": ' + json.dumps(record["run"]) + ",", '  "fields": ' + json.dumps(list(FIELDS)) + ",",
             '  "cells": [']
    cells = record["cells"]
    for i, row in enumerate(cells):
        lines.append("    " + json.dumps(row) + ("," if i + 1 < len(cells) else ""))
    lines += ["  ]", "}", ""]
    return "\n".join(lines)


def make_record(cells):
    return {"run": run_conditions(), "fields": list(FIELDS), "cells": cells_from_report(cells)}


def compare_cells(fresh_rows, recorded_rows):
    """Differences between two lists of record rows, as readable lines (empty when equal)."""
    a = {(r[0], r[1]): r for r in fresh_rows}
    b = {(r[0], r[1]): r for r in recorded_rows}
    out = []
    for key in sorted(set(a) | set(b)):
        if key not in b:
            out.append(f"{key[0]} / {key[1]}: in this run, not in the record")
        elif key not in a:
            out.append(f"{key[0]} / {key[1]}: in the record, not in this run")
        elif a[key] != b[key]:
            fields = ", ".join(f"{name} {b[key][i]} -> {a[key][i]}" for i, name in enumerate(FIELDS)
                               if i >= 2 and a[key][i] != b[key][i])
            out.append(f"{key[0]} / {key[1]}: {fields}")
    return out


# ---------------------------------------------------------------------------------------------------
# aggregation and rendering

def _registry():
    from arrowmetal import functions as F
    return F


def per_operation(record):
    """{op: [cases, pass, documented, unclassified, skipped]} over the record's cells."""
    out = OrderedDict()
    for row in record["cells"]:
        t = out.setdefault(row[0], [0, 0, 0, 0, 0])
        for i in range(5):
            t[i] += row[2 + i]
    return out


def per_function(record):
    """OrderedDict name -> {"ops": [...], "counts": [cases, pass, documented, unclassified, skipped]}
    in the registry's section order, for every Arrow name some operation counts toward."""
    F = _registry()
    ops = per_operation(record)
    by_name = {}
    for op_name, counts in ops.items():
        for name in OPERATION_FUNCTIONS.get(op_name, ()):
            entry = by_name.setdefault(name, {"ops": [], "counts": [0, 0, 0, 0, 0]})
            entry["ops"].append(op_name)
            for i in range(5):
                entry["counts"][i] += counts[i]
    out = OrderedDict()
    for section in F.SECTIONS:
        for f in F._REGISTRY.values():
            if f.section == section and f.name in by_name:
                out[f.name] = dict(by_name[f.name], section=section)
    return out


def totals(record):
    t = [0, 0, 0, 0, 0]
    for counts in per_operation(record).values():
        for i in range(5):
            t[i] += counts[i]
    return t


def _n(x):
    return f"{x:,}"


def _matrix_shape(record):
    ops = {r[0] for r in record["cells"]}
    types = {r[1] for r in record["cells"]}
    cases = sorted({r[2] for r in record["cells"]})
    return len(ops), len(types), len(record["cells"]), cases


def coverage_section(record):
    """The block between BEGIN and END in docs/COVERAGE.md."""
    F = _registry()
    run = record["run"]
    n_ops, n_types, n_cells, per_cell = _matrix_shape(record)
    cases, passed, documented, unclassified, skipped = totals(record)
    functions = per_function(record)
    ops = per_operation(record)
    outside = [o for o in ops if o in OUTSIDE]
    out = [BEGIN, "",
           f"The differential matrix (`python/tests/test_differential.py`, [TESTING.md](TESTING.md#3-the-differential-matrix)) "
           f"runs {n_ops} operations over {n_types} column types: {_n(n_cells)} (operation, type) cells, each over "
           f"{' / '.join(str(c) for c in per_cell)} datasets, {_n(cases)} cases. The run recorded in "
           f"`docs/data/differential_coverage.json` (ArrowMetal {run['arrowmetal']}, pyarrow {run['pyarrow']}, "
           f"{run['device']}, router `{run['router']}`): **{_n(passed)} pass, {_n(documented)} documented "
           f"divergences, {_n(skipped)} skipped, {_n(unclassified)} unclassified**.",
           "",
           "A case counts toward an Arrow function when the ArrowMetal call it runs is that function's "
           "implementation (the call column of [ARROW_FUNCTIONS.md](ARROW_FUNCTIONS.md)) or, for an ArrowMetal "
           "call with no Arrow name of its own (`sort`, `argsort`, `to_strings`), when its answer is compared "
           "with that function's result. One case can check several functions — a `compare_scalar` case runs "
           "all six comparisons — so the rows below add up to more than the case total. A documented "
           "divergence is a failing case that matches an open finding in [EVALUATION.md](EVALUATION.md); a "
           "skipped case is an operation that does not implement that column type.",
           "",
           f"{len(functions)} of the {len(F.list_functions())} Arrow function names have matrix cases. Every "
           "name, with or without them, is also run through `call_function` against `pyarrow.compute` in "
           "`python/tests/test_functions.py`.",
           "",
           "| Arrow function | Section | Matrix operations | Cases | Pass | Documented | Skipped |",
           "|---|---|---|---:|---:|---:|---:|"]
    for name, entry in functions.items():
        c = entry["counts"]
        out.append(f"| `{name}` | {entry['section']} | {', '.join(f'`{o}`' for o in entry['ops'])} | "
                   f"{_n(c[0])} | {_n(c[1])} | {_n(c[2])} | {_n(c[4])} |")
    out += ["",
            f"The {len(outside)} operations that check no Arrow compute function, with what they check:",
            "",
            "| Matrix operation | What it checks | Cases | Pass | Documented | Skipped |",
            "|---|---|---:|---:|---:|---:|"]
    for o in outside:
        c = ops[o]
        out.append(f"| `{o}` | {OUTSIDE[o]} | {_n(c[0])} | {_n(c[1])} | {_n(c[2])} | {_n(c[4])} |")
    out += ["", f"Regenerate with `{COMMAND}` (runs the matrix); `--check` compares a fresh run with the "
                "record and writes nothing.", "", END]
    return "\n".join(out)


def arrow_functions_section(record):
    """The per-section summary docs/ARROW_FUNCTIONS.md carries (function_table_report.py --page)."""
    F = _registry()
    functions = per_function(record)
    cases, passed, documented, unclassified, skipped = totals(record)
    out = ["## Differential matrix cases, by section", "",
           f"Separately from the row-by-row calls above, `python/tests/test_differential.py` runs every "
           f"ArrowMetal operation over generated columns of every type it accepts: {_n(cases)} cases in the "
           f"recorded run, {_n(passed)} pass, {_n(documented)} documented divergences, {_n(skipped)} skipped, "
           f"{_n(unclassified)} unclassified. [COVERAGE.md](COVERAGE.md#differential-cases-per-arrow-function) "
           "has the count for each name; this is how many names in each section the matrix reaches.",
           "",
           "| Section | Names | With matrix cases | Names without |",
           "|---|---:|---:|---|"]
    for section in F.SECTIONS:
        names = [f.name for f in F._REGISTRY.values() if f.section == section]
        reached = [n for n in names if n in functions]
        missing = [n for n in names if n not in functions]
        out.append(f"| {section} | {len(names)} | {len(reached)} | "
                   f"{', '.join(f'`{n}`' for n in missing) or '-'} |")
    total = len(F.list_functions())
    out.append(f"| **Total** | **{total}** | **{len(functions)}** | |")
    return "\n".join(out)


def replace_block(text, block):
    start, stop = text.find(BEGIN), text.find(END)
    if start < 0 or stop < 0:
        raise SystemExit(f"{COVERAGE_MD} has no {BEGIN} ... {END} block")
    return text[:start] + block + text[stop + len(END):]


def render_pages(record):
    """{path: content} for the two generated pages."""
    import function_table_report
    with open(COVERAGE_MD) as fh:
        coverage = replace_block(fh.read(), coverage_section(record))
    return {COVERAGE_MD: coverage, ARROW_FUNCTIONS_MD: function_table_report.page(record) + "\n"}


def write_pages(record):
    for path, content in render_pages(record).items():
        with open(path, "w") as fh:
            fh.write(content)


# ---------------------------------------------------------------------------------------------------

def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="run the matrix and compare with the record")
    mode.add_argument("--render", action="store_true", help="rewrite the pages from the record, no run")
    args = parser.parse_args(argv)

    if args.render:
        write_pages(load_record())
        print(f"rendered {COVERAGE_MD} and {ARROW_FUNCTIONS_MD} from {RECORD}")
        return 0

    problem = default_matrix_problem()
    if problem:
        print(f"coverage_report: {problem}", file=sys.stderr)
        return 2
    import differential_report
    cells, ops, types, total, elapsed = differential_report.run(quiet=True)
    record = make_record(cells)
    t = totals(record)
    print(f"total: {t[0]} cases  |  pass {t[1]}  documented {t[2]}  unclassified {t[3]}  skip {t[4]}  |  "
          f"{elapsed:.1f}s")
    if args.check:
        diffs = compare_cells(record["cells"], load_record()["cells"])
        print("coverage table: " + ("matches the record" if not diffs else f"STALE in {len(diffs)} cell(s)"))
        for line in diffs[:40]:
            print("  " + line)
        return 1 if diffs else 0
    if t[3]:
        print("coverage_report: unclassified divergences; run differential_report.py and classify them first",
              file=sys.stderr)
        return 1
    os.makedirs(os.path.dirname(RECORD), exist_ok=True)
    with open(RECORD, "w") as fh:
        fh.write(dump_record(record))
    write_pages(record)
    print(f"wrote {RECORD}, {COVERAGE_MD} and {ARROW_FUNCTIONS_MD}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
