#!/usr/bin/env python3
"""Print the Arrow function-name registry as Markdown, ready to paste into docs/COVERAGE.md.

    PYTHONPATH=python python python/tests/function_table_report.py            # summary + full table
    PYTHONPATH=python python python/tests/function_table_report.py --summary  # counts only
    PYTHONPATH=python python python/tests/function_table_report.py Sorts Selections

With section names it prints only those sections, in the order given. The numbers come from
`arrowmetal.functions`, the same table `python/tests/test_functions.py` calls row by row, so a status
here has been executed against pyarrow.compute rather than asserted.
"""
import sys

from arrowmetal import functions as F


def main(argv):
    args = [a for a in argv[1:] if not a.startswith("--")]
    flags = {a for a in argv[1:] if a.startswith("--")}
    unknown = [s for s in args if s not in F.SECTIONS]
    if unknown:
        sys.stderr.write(f"unknown section(s): {', '.join(unknown)}\n"
                         f"known sections: {', '.join(F.SECTIONS)}\n")
        return 2
    print(f"<!-- generated by python/tests/function_table_report.py; "
          f"{len(F.list_functions())} Arrow function names -->")
    print()
    print(F.summary_markdown())
    if "--summary" not in flags:
        print()
        print(F.markdown_table(args or None))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
